name: Hello-world
# on – определяет события, которые запускают воркфлоу
on:
  - push
  - pull_request

jobs:
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [3.9, 3.10]
    steps:
       # checkout — клонирует репозиторий
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        # run –  bash-команда для выполнения задания
        run: |
          pip install poetry
          make install
          pip install pytest
      - name: Run linter and pytest
        run: make lint
      - name: Test cover  
        run: |
          make check
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: 1d6cb791c486a1e08ee3fd329db1724658b1c3ac60d2e1be1f8a446751d14d8e
        with:
          coverageCommand: make test-coverage
          debug: true
